name: UI Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    name: Run Playwright UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          playwright install --with-deps
      - name: Run tests and generate HTML report
        run: |
          pytest tests/ --html=report.html --self-contained-html

      - name: Upload test report html
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: report.html
        if: always()


      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: "*.png"
        if: always()